### ISSUE TITLE
docker login doesn't work anymore

### ISSUE THREAD

**Issue by zadigus** [softozor/shopozor-ci#2]
Upon `docker login -u *** -p ***` in our Jenkins pipeline, we get the following error

```
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

This is curious because it worked fine until yesterday. Even a ping to the docker registry url fails. However, it works fine on my development laptop. 

The work-around will be that we will self-host our docker registry to avoid that kind of problems.

**Comment by zadigus** [comment]
It doesn't work either if I

* disable the environment's firewall.
* attach an IPv4 to the jenkins node

**Comment by donnerc** [comment]
Do you try to ping the host from the server and did you try basic
networking troubleshooting ? Perhaps DNS resolution ?

**Comment by zadigus** [comment]
What I also tried is to completely re-install the Jelastic environment. The problem persisted.

**Comment by zadigus** [comment]
Answer of Jelastic provider (ticket [## 9149 ##]): 

```
Alors le problème du docker login sur le Docker hub était lié à une mauvaise configuration de DNS Recursor (ce problème a été fixé). 
```
