### ISSUE TITLE
Use of import file in zip format in reportportal.io

### ISSUE THREAD

**Issue by likitha-dot** [softozor/shopozor-ci#32]
I used the import  functionality to importing a zip file. That zip file contains test cases, reportportal.properties file, drivers, pom.xml file and also a testNg.xml file but i didn't get any update can anyone suggest me or explain me how  to use this import functionality in reportportal.io

**Comment by likitha-dot** [comment]
I used the import functionality to importing a zip file. I have zipped my complete project file  but i didn't get any update can anyone suggest
<img width="640" alt="demo_maven" src="https://user-images.githubusercontent.com/59014290/71089421-d6d8e000-21c6-11ea-89be-7eede508f6be.png">
 me or explain me how to use this import functionality in reportportal.io

**Comment by zadigus** [comment]
We have not yet started working with reportportal, so we have no idea about it yet.

**Comment by likitha-dot** [comment]
I used the import functionality to importing a zip file. I have zipped my complete project file but i didn't get any update can anyone suggest 
<img width="640" alt="demo_maven" src="https://user-images.githubusercontent.com/59014290/71144659-d67f2a00-2244-11ea-9b0a-cd3ff6ba97b5.png">
me or explain me how to use this import functionality in reportportal.io
